### ISSUE TITLE
ERROR AL EJECUTAR CODIGO

### ISSUE THREAD

**Issue by naui2003** [maestria-geotel-201902/unidad-0-asignacion-3-mi-primer-rmd-naui2003#1]
Buenas noches,  profesor al llegar a este punto se me genera el error anexo. Esta sombreado una parte del código, pero lo ejecuté completo. 
![image](https://user-images.githubusercontent.com/39661108/67171605-e0d89100-f385-11e9-8a8f-1c8da596d7b8.png)

**Comment by geofis** [comment]
Gracias por notificar. Estuve haciendo mantenimientos nocturnos al servidor. Debería funcionar ya. Si hubiese inconvenientes, favor reabrir el issue.

**Comment by geofis** [comment]
@naui2003 Prueba con el nuevo repo, y avisa si no funciona.
